CREATE DEFINER=`root`@`localhost` FUNCTION `travel`(novaccine INT) RETURNS varchar(40) CHARSET utf8mb4
    DETERMINISTIC
BEGIN
IF(novaccine=2)
THEN
RETURN ("ALIGIBLE FOR GOING ABROAD");
ELSE 
RETURN ("NOT ALIGIBLE FOR GOING ABR0AD");
END IF;
END